"""
Plain-English forensic verdict for a verification result, generated by IBM
Granite running locally via Ollama. No cloud, no credentials, works offline.

If Granite/Ollama is not reachable, we fall back to a deterministic rule-based
summary and label it honestly (model = "rule-based") rather than pretending an
AI produced it.
"""

import json
import urllib.request

OLLAMA_BASE = "http://localhost:11434"
GRANITE_MODEL = "granite3.3:2b"


def _build_prompt(v, cert):
    qp = (cert or {}).get("quantum_proof", {})
    backend = qp.get("backend", "quantum backend")
    chsh = v.get("chsh_value", qp.get("chsh_value"))
    verdict = "AUTHENTIC" if v.get("overall") else "FORGED"
    checks = (
        f"- Document fingerprint match: {v.get('hash_match')}\n"
        f"- Bell-CHSH inequality violated: {v.get('bell_violated')} (value {chsh}, classical bound 2.0, quantum max 2.828)\n"
        f"- Circuit angles bound to this document: {v.get('document_bound')}\n"
        f"- Post-quantum signature valid: {v.get('signature_valid')} (scheme {v.get('signature_scheme')})\n"
        f"- Quantum backend: {backend}\n"
        f"- Overall determination: {verdict}"
    )
    return (
        "You are a quantum-forensics analyst. Write a concise, confident forensic "
        "verdict of 2 to 3 sentences for the document-verification result below. "
        "Reference the CHSH value explicitly and explain in plain language what it "
        "proves. Do not use bullet points or headings. End with a final line in the "
        "exact form 'VERDICT: AUTHENTIC' or 'VERDICT: FORGED'.\n\n"
        f"Verification data:\n{checks}\n"
    )


def _rule_based_verdict(v, cert):
    qp = (cert or {}).get("quantum_proof", {})
    chsh = v.get("chsh_value", qp.get("chsh_value"))
    backend = qp.get("backend", "a quantum backend")
    if v.get("overall"):
        return (
            f"The document's fingerprint matches the certificate, and the Bell-CHSH score of "
            f"{chsh} measured on {backend} exceeds the classical bound of 2.0 — a correlation "
            f"no classical process can fake. The circuit was bound to this specific document and "
            f"the post-quantum signature ({v.get('signature_scheme')}) is valid. "
            f"VERDICT: AUTHENTIC"
        )
    reasons = []
    if not v.get("hash_match"):
        reasons.append("the document fingerprint does not match the certificate")
    if not v.get("bell_violated"):
        reasons.append(f"the CHSH score {chsh} sits below the classical bound of 2.0")
    if v.get("document_bound") is False:
        reasons.append("the circuit angles were not derived from this document")
    if not v.get("signature_valid"):
        reasons.append("the post-quantum signature is invalid")
    why = "; ".join(reasons) or "one or more checks failed"
    return (
        f"This certificate does not authenticate the presented document: {why}. "
        f"The quantum and cryptographic evidence do not support authenticity. "
        f"VERDICT: FORGED"
    )


def generate_forensic_verdict(verification, certificate):
    v = verification or {}
    cert = certificate or {}
    prompt = _build_prompt(v, cert)
    try:
        body = json.dumps({
            "model": GRANITE_MODEL,
            "prompt": prompt,
            "stream": False,
            "options": {"temperature": 0.2, "num_predict": 220},
        }).encode()
        req = urllib.request.Request(
            f"{OLLAMA_BASE}/api/generate", data=body,
            headers={"Content-Type": "application/json"},
        )
        resp = json.load(urllib.request.urlopen(req, timeout=90))
        text = (resp.get("response") or "").strip()
        if text:
            return {"verdict": text, "model": "IBM Granite 3.3"}
    except Exception:
        pass
    return {"verdict": _rule_based_verdict(v, cert), "model": "rule-based"}
